registration:
  server:
    hostname: localhost

spring:
  config:
    name: discovery-server


eureka:
  instance:
    hostname: localhost
  client: 
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 1111  

