spring:
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10   # DO NOT DO THIS IN PRODUCTION

server:
  port: 9999

warehouseRoute: LOADBALANCER

cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          
# RESILIENCE4J PROPERTIES
resilience4j:
  circuitbreaker:
    configs:
      default:
        #registerHealthIndicator: true
        ringBufferSizeInClosedState: 10
        ringBufferSizeInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenStateMillis: 2000
        failureRateThreshold: 5
        eventConsumerBufferSize: 10
    instances:
      helloworld:
        baseConfig: default
        ringBufferSizeInClosedState: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
      expose: "*"
